# Generated by Django 5.1.1 on 2024-09-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('two_digit_top', 'Two-Digit Top'), ('two_digit_bottom', 'Two-Digit Bottom'), ('three_digit_top', 'Three-Digit Top'), ('three_digit_mix', 'Three-Digit Mix'), ('top_run', 'Top Run'), ('bottom_run', 'Bottom Run')], max_length=20)),
                ('bet_number', models.CharField(max_length=10)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
