# Generated by Django 5.1.1 on 2024-09-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='country',
            field=models.CharField(choices=[('thailand', 'Thailand'), ('usa', 'USA'), ('uk', 'UK'), ('vietnam', 'Vietnam'), ('laos', 'Laos')], default='thailand', max_length=20),
        ),
    ]
