# Generated by Django 5.1.1 on 2024-09-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_bet_amount_alter_bet_bet_type_alter_bet_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหวย')),
                ('close_time', models.TimeField(verbose_name='เวลาปิดรับ')),
                ('result_time', models.TimeField(verbose_name='เวลาออกผล')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lottery_images/', verbose_name='รูปภาพหวย')),
            ],
            options={
                'verbose_name': 'หวย',
                'verbose_name_plural': 'หวยทั้งหมด',
            },
        ),
        migrations.AlterModelOptions(
            name='bet',
            options={'verbose_name': 'การแทงหวย', 'verbose_name_plural': 'การแทงหวยทั้งหมด'},
        ),
    ]
