# Generated by Django 5.1.1 on 2024-09-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_lottery_alter_bet_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ประเภทหวย')),
            ],
            options={
                'verbose_name': 'ประเภทหวย',
                'verbose_name_plural': 'ประเภทหวยทั้งหมด',
            },
        ),
        migrations.AddField(
            model_name='lottery',
            name='lottery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lottery.lotterytype', verbose_name='ประเภทหวย'),
        ),
    ]
