# Generated by Django 5.1.1 on 2024-09-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_lotterytype_lottery_lottery_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bet',
        ),
        migrations.AlterModelOptions(
            name='lottery',
            options={'verbose_name': 'หวย', 'verbose_name_plural': 'หวย'},
        ),
        migrations.AlterModelOptions(
            name='lotterytype',
            options={'verbose_name': 'ประเภทหวย', 'verbose_name_plural': 'ประเภทหวย'},
        ),
    ]
