# Generated by Django 5.1.1 on 2024-09-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0009_bet_back_scrape_bet_buyer_name_bet_double_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='back_scrape',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='bottom',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='double_number',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='front_scrape',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='nineteen_door',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='reverse_number',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='running_number',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='six_back',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='top',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='triple_number',
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ประเภทการเดิมพัน'),
        ),
    ]
