# Generated by Django 5.1.1 on 2024-09-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0010_remove_bet_back_scrape_remove_bet_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='position',
            field=models.CharField(blank=True, choices=[('บน', 'บน'), ('ล่าง', 'ล่าง')], max_length=10, null=True, verbose_name='ตำแหน่ง'),
        ),
    ]
