# Generated by Django 5.1.1 on 2024-09-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0011_bet_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='bet_type',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='position',
        ),
        migrations.AddField(
            model_name='bet',
            name='bottom',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ล่าง'),
        ),
        migrations.AddField(
            model_name='bet',
            name='top',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='บน'),
        ),
    ]
